"""add_extraction_queries_table

Revision ID: 2ab37517a69d
Revises: d3ec8d2ba934
Create Date: 2025-11-27 14:40:19.633163
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ab37517a69d'
down_revision = 'd3ec8d2ba934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el tipo ENUM solo si no existe
    extraction_status_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='extractionstatus', create_type=False)
    extraction_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('extraction_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_topic', sa.String(length=500), nullable=False),
    sa.Column('status', extraction_status_enum, nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('arq_job_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('query_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_queries_user_id'), 'extraction_queries', ['user_id'], unique=False)
    # Solo eliminar searchlog si existe
    try:
        op.drop_index(op.f('ix_searchlog_user_id'), table_name='searchlog')
        op.drop_table('searchlog')
    except Exception:
        # Si la tabla no existe, continuar
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('searchlog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchlog_pkey'))
    )
    op.create_index(op.f('ix_searchlog_user_id'), 'searchlog', ['user_id'], unique=False)
    op.drop_index(op.f('ix_extraction_queries_user_id'), table_name='extraction_queries')
    op.drop_table('extraction_queries')
    # ### end Alembic commands ###

