"""add subscription fields to user

Revision ID: 67614d122950
Revises: 
Create Date: 2025-11-27 11:16:12.170718
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67614d122950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_searchlog_user_id'), table_name='searchlog')
    op.drop_table('searchlog')
    
    # Create ENUM types if they don't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE plan_tier AS ENUM ('MOTOR', 'CEREBRO', 'PARTNER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE subscription_status AS ENUM ('ACTIVE', 'PAST_DUE', 'CANCELED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Add new columns
    op.add_column('user', sa.Column('subscription_status', postgresql.ENUM('ACTIVE', 'PAST_DUE', 'CANCELED', name='subscription_status', create_type=False), nullable=True))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Convert plan_tier from VARCHAR to ENUM
    # First, ensure all existing values are valid or set to default
    op.execute("""
        UPDATE "user" 
        SET plan_tier = 'MOTOR' 
        WHERE plan_tier IS NULL OR plan_tier NOT IN ('MOTOR', 'CEREBRO', 'PARTNER')
    """)
    
    # Now alter the column with explicit USING clause
    op.execute("""
        ALTER TABLE "user" 
        ALTER COLUMN plan_tier TYPE plan_tier 
        USING plan_tier::plan_tier
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'plan_tier',
               existing_type=sa.Enum('MOTOR', 'CEREBRO', 'PARTNER', name='plan_tier'),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('user', 'features')
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'subscription_status')
    op.create_table('searchlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('searchlog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchlog_pkey'))
    )
    op.create_index(op.f('ix_searchlog_user_id'), 'searchlog', ['user_id'], unique=False)
    # ### end Alembic commands ###

