"""add_content_planner_campaigns_table

Revision ID: 86754679b0c8
Revises: b0d8386e7c4c
Create Date: 2025-11-27 16:27:58.616760
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86754679b0c8'
down_revision = 'b0d8386e7c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # El enum 'campaignstatus' ya existe de la migración de content_creator
    # Usar el enum existente
    campaign_status_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus', create_type=False)
    
    # Crear tabla content_planner_campaigns
    op.create_table('content_planner_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('tone_of_voice', sa.String(length=100), nullable=False),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', campaign_status_enum, nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('arq_job_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('content_planner_campaigns_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('content_planner_campaigns_pkey'))
    )
    op.create_index(op.f('ix_content_planner_campaigns_user_id'), 'content_planner_campaigns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_planner_campaigns_user_id'), table_name='content_planner_campaigns')
    op.drop_table('content_planner_campaigns')
    # ### end Alembic commands ###

