"""add_extraction_queries_table_fix

Revision ID: b0d8386e7c4c
Revises: 2ab37517a69d
Create Date: 2025-11-27 14:41:33.644928
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0d8386e7c4c'
down_revision = '2ab37517a69d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_searchlog_user_id'), table_name='searchlog')
    op.drop_table('searchlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('searchlog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchlog_pkey'))
    )
    op.create_index(op.f('ix_searchlog_user_id'), 'searchlog', ['user_id'], unique=False)
    # ### end Alembic commands ###

