"""add_usage_logs_table

Revision ID: b86e9a43883c
Revises: 67614d122950
Create Date: 2025-11-27 13:22:57.908642
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b86e9a43883c'
down_revision = '67614d122950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Usar if_exists=True para evitar errores si el índice o tabla ya no existen
    op.drop_index(op.f('ix_searchlog_user_id'), table_name='searchlog', if_exists=True)
    op.drop_table('searchlog', if_exists=True)
    op.alter_column('user', 'plan_tier',
               existing_type=postgresql.ENUM('MOTOR', 'CEREBRO', 'PARTNER', name='plan_tier'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'plan_tier',
               existing_type=postgresql.ENUM('MOTOR', 'CEREBRO', 'PARTNER', name='plan_tier'),
               nullable=False)
    op.create_table('searchlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('searchlog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchlog_pkey'))
    )
    op.create_index(op.f('ix_searchlog_user_id'), 'searchlog', ['user_id'], unique=False)
    # ### end Alembic commands ###

