"""genesis_schema

Revision ID: cf9428b5de35
Revises: 
Create Date: 2025-11-30 12:58:01.331580
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf9428b5de35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentpiece_campaign_id'), table_name='contentpiece')
    op.drop_table('contentpiece')
    op.drop_index(op.f('ix_content_planner_campaigns_month'), table_name='content_planner_campaigns')
    op.drop_index(op.f('ix_content_planner_campaigns_user_id'), table_name='content_planner_campaigns')
    op.drop_table('content_planner_campaigns')
    op.drop_index(op.f('ix_searchlog_user_id'), table_name='searchlog')
    op.drop_table('searchlog')
    op.drop_index(op.f('ix_marketingcampaign_user_id'), table_name='marketingcampaign')
    op.drop_table('marketingcampaign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketingcampaign',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('marketingcampaign_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('influencer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tone_of_voice', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platforms', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('content_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='marketingcampaign_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='marketingcampaign_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_marketingcampaign_user_id'), 'marketingcampaign', ['user_id'], unique=False)
    op.create_table('searchlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('searchlog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('searchlog_pkey'))
    )
    op.create_index(op.f('ix_searchlog_user_id'), 'searchlog', ['user_id'], unique=False)
    op.create_table('content_planner_campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tone_of_voice', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('arq_job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('campaign_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('content_planner_campaigns_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('content_planner_campaigns_pkey'))
    )
    op.create_index(op.f('ix_content_planner_campaigns_user_id'), 'content_planner_campaigns', ['user_id'], unique=False)
    op.create_index(op.f('ix_content_planner_campaigns_month'), 'content_planner_campaigns', ['month'], unique=False)
    op.create_table('contentpiece',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('visual_script', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketingcampaign.id'], name=op.f('contentpiece_campaign_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contentpiece_pkey'))
    )
    op.create_index(op.f('ix_contentpiece_campaign_id'), 'contentpiece', ['campaign_id'], unique=False)
    # ### end Alembic commands ###

